/*---------------------------------------------------------------------------------------------
 *  Construct IDE - Git Service (Git Integration via CLI)
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

import { TerminalExecutor, TerminalResult } from './TerminalExecutor';

export interface GitStatus {
	branch: string;
	staged: string[];
	unstaged: string[];
	untracked: string[];
}

export interface GitCommitResult {
	success: boolean;
	hash: string;
	message: string;
}

export class GitError extends Error {
	constructor(message: string) {
		super(message);
		this.name = 'GitError';
	}
}

export class GitService {
	constructor(
		private readonly terminal: TerminalExecutor,
		private readonly workspaceRoot: string,
	) {}

	/**
	 * Get the current git status.
	 */
	async getStatus(): Promise<GitStatus> {
		const result = await this.runGit(['status', '--porcelain=v2', '--branch']);
		if (result.exitCode !== 0) {
			throw new GitError(`git status failed: ${result.stderr}`);
		}

		const branch = this.parseBranch(result.stdout);
		const { staged, unstaged, untracked } = this.parsePorcelain(result.stdout);

		return { branch, staged, unstaged, untracked };
	}

	/**
	 * Stage specific files.
	 */
	async add(files: string[]): Promise<void> {
		const result = await this.runGit(['add', ...files]);
		if (result.exitCode !== 0) {
			throw new GitError(`git add failed: ${result.stderr}`);
		}
	}

	/**
	 * Stage all changes.
	 */
	async addAll(): Promise<void> {
		const result = await this.runGit(['add', '-A']);
		if (result.exitCode !== 0) {
			throw new GitError(`git add -A failed: ${result.stderr}`);
		}
	}

	/**
	 * Create a commit with the given message.
	 */
	async commit(message: string): Promise<GitCommitResult> {
		const result = await this.runGit(['commit', '-m', message]);
		if (result.exitCode !== 0) {
			return { success: false, hash: '', message: result.stderr };
		}

		const hash = this.parseCommitHash(result.stdout);
		return { success: true, hash, message };
	}

	/**
	 * Undo the last commit (soft reset — keeps changes staged).
	 */
	async undoLastCommit(): Promise<void> {
		const result = await this.runGit(['reset', '--soft', 'HEAD~1']);
		if (result.exitCode !== 0) {
			throw new GitError(`git reset failed: ${result.stderr}`);
		}
	}

	/**
	 * Undo the most recent file change using git checkout.
	 * This reverts a specific file to its state in HEAD.
	 */
	async revertFile(filePath: string): Promise<void> {
		const result = await this.runGit(['checkout', 'HEAD', '--', filePath]);
		if (result.exitCode !== 0) {
			throw new GitError(`git checkout failed: ${result.stderr}`);
		}
	}

	/**
	 * Get the diff of staged changes.
	 */
	async getStagedDiff(): Promise<string> {
		const result = await this.runGit(['diff', '--cached']);
		return result.stdout;
	}

	/**
	 * Get the diff of unstaged changes.
	 */
	async getUnstagedDiff(): Promise<string> {
		const result = await this.runGit(['diff']);
		return result.stdout;
	}

	/**
	 * Get the list of changed files in the last commit.
	 */
	async getLastCommitFiles(): Promise<string[]> {
		const result = await this.runGit(['diff-tree', '--no-commit-id', '--name-only', '-r', 'HEAD']);
		if (result.exitCode !== 0) {
			return [];
		}
		return result.stdout.split('\n').filter(Boolean);
	}

	/**
	 * Stage and commit all changes with a conventional commit message.
	 * The message is generated by the LLM in a real flow.
	 */
	async autoCommit(message: string): Promise<GitCommitResult> {
		await this.addAll();
		return this.commit(message);
	}

	private async runGit(args: string[]): Promise<TerminalResult> {
		return this.terminal.run('git', args, {
			cwd: this.workspaceRoot,
			timeoutMs: 30_000,
		});
	}

	private parseBranch(output: string): string {
		const match = output.match(/# branch.head\s+(\S+)/);
		return match ? match[1] : 'unknown';
	}

	private parsePorcelain(output: string): { staged: string[]; unstaged: string[]; untracked: string[] } {
		const staged: string[] = [];
		const unstaged: string[] = [];
		const untracked: string[] = [];

		for (const line of output.split('\n')) {
			if (line.startsWith('1 ')) {
				// Changed entry: 1 <xy> <sub> <mH> <mI> <mW> <hH> <hI> <path>
				const parts = line.split(/\s+/);
				const xy = parts[1];
				const filePath = parts.slice(8).join(' ');

				if (xy[0] !== '.' && xy[0] !== '?') {
					staged.push(filePath);
				}
				if (xy[1] !== '.' && xy[1] !== '?') {
					unstaged.push(filePath);
				}
			} else if (line.startsWith('? ')) {
				const filePath = line.slice(2).trim();
				untracked.push(filePath);
			}
		}

		return { staged, unstaged, untracked };
	}

	private parseCommitHash(output: string): string {
		const match = output.match(/\[[\w-]+ ([a-f0-9]{7,40})\]/);
		return match ? match[1] : '';
	}
}
